require "exercises"

print("Testing change()")
assert(change(0) == 0, 0, 0, 0)
_, err = pcall(change, 3.5)
assert(string.match(err, "Amount must be an integer"))
_, err = pcall(change, -50)
assert(string.match(err, "Amount cannot be negative"))
assert(change(1) == 0, 0, 0, 1)
assert(change(99) == 3, 2, 0, 4)
assert(change(42) == 1, 1, 1, 2)
assert(change(100000000037) == 4000000001, 1, 0, 2)
assert(change(10000000000005) == 400000000000, 0, 1, 0)

-- Uncomment the following tests as you complete the exercises
-- and remove this comment that tells you to uncomment!

-- print("Testing stretched()")
-- assert(stretched("") == "")
-- assert(stretched("  ") == "")
-- assert(stretched("  \t\n  \t") == "")
-- assert(stretched("  Hi  hi  ") == "Hiihhhiiii")
-- assert(stretched("😁😂😱") == "😁😂😂😱😱😱")
-- assert(stretched("hello world") ==
--     "heelllllllooooowwwwwwooooooorrrrrrrrllllllllldddddddddd")

-- print("Testing powers_generator()")
-- gen = powers_generator(3, 100)
-- status = coroutine.status(gen)
-- success, power = coroutine.resume(gen)
-- assert(status == "suspended" and success and power == 1)
-- status = coroutine.status(gen)
-- success, power = coroutine.resume(gen)
-- assert(status == "suspended" and success and power == 3)
-- status = coroutine.status(gen)
-- success, power = coroutine.resume(gen)
-- assert(status == "suspended" and success and power == 9)
-- status = coroutine.status(gen)
-- success, power = coroutine.resume(gen)
-- assert(status == "suspended" and success and power == 27)
-- status = coroutine.status(gen)
-- success, power = coroutine.resume(gen)
-- assert(status == "suspended" and success and power == 81)
-- status = coroutine.status(gen)
-- success, power = coroutine.resume(gen)
-- assert(status == "suspended" and success and power == nil)
-- status = coroutine.status(gen)
-- success, power = coroutine.resume(gen)
-- assert(status == "dead" and not success)

-- print("Testing say()")
-- assert(say() == "")
-- assert(say("hi")() == "hi")
-- assert(say("hi")("there")() == "hi there")
-- assert(say("hello")("my")("name")("is")("Colette")() == "hello my name is Colette")
-- assert(say("h i")() == "h i")
-- assert(say("hi ")("   there")() == "hi     there")
-- assert(say("")("")("dog")("")("go")(), "  dog  go")
-- assert(say("😄🤗")("💀👊🏾")() == "😄🤗 💀👊🏾")

-- print("Testing misc_file_stats()")
-- stats = misc_file_stats("NoSuchFile.txt")
-- assert(stats.error == "No such file")
-- stats = misc_file_stats("../test-for-line-count.txt")
-- print(stats.lineCount, stats.blankLineCount, stats.hashedLineCount)
-- assert(stats.lineCount == 13 and stats.blankLineCount == 7 and stats.hashedLineCount == 2)

-- // describe("The miscFileStats function", async () => {
-- //   it("returns an object with an error if no such file", async () => {
-- //     const stats = await miscFileStats("NoSuchFile.txt")
-- //     deepEqual(stats, { error: "No such file" })
-- //   })
-- //   it("computes stats for the test file", async () => {
-- //     const stats = await miscFileStats("../test-for-line-count.txt")
-- //     deepEqual(stats, { lineCount: 13, blankLineCount: 7, hashedLineCount: 2 })
-- //   })
-- // })

-- print("Testing Quaternion")
-- q1 = Quaternion.new(8, 5, -3, 1)
-- assert(table.concat(q1:coefficients(), ",") == "8,5,-3,1")
-- q2 = Quaternion.new(0, 0, 0, 0)
-- assert(table.concat(q2:coefficients(), ",") == "0,0,0,0")
-- q3 = Quaternion.new(13, 21, -5, -21)
-- q4 = Quaternion.new(2, -1, -55, 2.5)
-- assert(table.concat((q3 + q4):coefficients(), ",") == "15,20,-60,-18.5")
-- q5 = Quaternion.new(3, -5, 1, -8)
-- q6 = Quaternion.new(2, -13, -2, 3)
-- assert(table.concat((q5 * q6):coefficients(), ",") == "-33,-62,115,16")

print("All tests pass")
